<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DevForge.Application\DevForge.Application.csproj" />
    <ProjectReference Include="..\DevForge.Blueprints.BuiltIn\DevForge.Blueprints.BuiltIn.csproj" />
    <ProjectReference Include="..\DevForge.Infrastructure\DevForge.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="docs\README.md"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\CHANGELOG.md" Link="docs\CHANGELOG.md"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
