<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DevForge.Blueprints.Abstractions\DevForge.Blueprints.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\blueprints\**\*">
      <Link>blueprints\built-in\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
