<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DevForge.Domain\DevForge.Domain.csproj" />
    <ProjectReference Include="..\DevForge.Blueprints.Abstractions\DevForge.Blueprints.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
