// <auto-generated />
using DevForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DevForgeDbContext))]
    [Migration("20260814025832_PersistPublicationCheckpoints")]
    partial class PersistPublicationCheckpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedValue")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppSettings_ValueKind", "ValueKind IN ('Text', 'BooleanFlag', 'WholeNumber', 'JsonObject')");
                        });
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.BlueprintEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<long>("DiscoveredAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trust")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "Version");

                    b.ToTable("Blueprints", (string)null);
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.EnvironmentToolEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScannedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUnixMs");

                    b.ToTable("EnvironmentTools", (string)null);
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.IdeInstallationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ScannedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IdeInstallations", (string)null);
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.PresetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Presets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Presets_SchemaVersion", "SchemaVersion > 0");
                        });
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.ProjectRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueprintChecksum")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueprintId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueprintPackageDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueprintSourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueprintTrust")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueprintVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrossVolumeTemporaryPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStepId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalizationState")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnershipMarkerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnershipMarkerPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanBodyChecksum")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanHash")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanPreviewBodyChecksum")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanPreviewJson")
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationBodyChecksum")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationJson")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportState")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunArtifactRoot")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("StagingPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("StagingPayloadPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetParentRoot")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "UpdatedAtUnixMs");

                    b.ToTable("ProjectRuns", (string)null);
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.RecentProjectEntity", b =>
                {
                    b.Property<string>("ProjectPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastOpenedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectPath");

                    b.HasIndex("LastOpenedAtUnixMs");

                    b.ToTable("RecentProjects", (string)null);
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.RunStepEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorContextJson")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ErrorIsRetryable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorPhase")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorStepId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSuggestedActionsJson")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorTechnicalDetail")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDigest")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("RunId", "StepId", "AttemptNumber");

                    b.HasIndex("RunId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("RunSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_RunSteps_AttemptNumber", "AttemptNumber > 0");
                        });
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.TeamProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TeamProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeamProfiles_SchemaVersion", "SchemaVersion > 0");
                        });
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.RunStepEntity", b =>
                {
                    b.HasOne("DevForge.Infrastructure.Persistence.Entities.ProjectRunEntity", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DevForge.Infrastructure.Persistence.Entities.ProjectRunEntity", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
