import argparse
import logging
from collections.abc import Sequence

from team_tool.config import AppConfig
from team_tool.logging_config import configure_logging


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="team-tool",
        description="A production Python CLI generated by DevForge Studio.",
    )
    parser.add_argument("--version", action="version", version="%(prog)s 0.1.0")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    build_parser().parse_args(argv)
    config = AppConfig.from_environment()
    configure_logging(config)
    logging.getLogger(__name__).info("Team Tool is ready.")
    return 0
