<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TeamTool.Application\TeamTool.Application.csproj" />
    <ProjectReference Include="..\..\src\TeamTool.Domain\TeamTool.Domain.csproj" />
    <ProjectReference Include="..\..\src\TeamTool.Desktop\TeamTool.Desktop.csproj" />
  </ItemGroup>
</Project>
